baseURL = "https://YaganArun.github.io/mlnotes/"
languageCode = "en-us"
title = "Yagan Arun"
theme = "berbera"

pygmentsCodeFences=true
pygmentsUseClasses=true
canonifyURLs=true
publishDir="docs"
disableKinds = ["section", "taxonomy", "taxonomyTerm"]
